### PR TITLE
Usx to json

### PR DESCRIPTION
**Pull request by kavitharaju**
This PR includes the following changes
-   Avoid text and use only content
-   Avoid empty content array
-   Do not remove milestone end elements
-   Print unicode properly in JSON output
-   Call the format USJ and version number alpha.2

Moving to a branch and merge workflow

### CODE REVIEW

**Comment by mvahowe** [comment]
@kavitharaju I'm seeing the following:
```
python3.8 usx_to_json.py 
  File "usx_to_json.py", line 29
    match what_to_do:
```
Any suggestions?

**Comment by kavitharaju** [comment]
I am using python 3.10. this match statement is a new feature introduced in 3.9 I think. 

Will it be possible for you to upgrade your python or have multiple versions installed?

**Comment by mvahowe** [comment]
@kavitharaju Turns out I have Python 3.10 too (Ubuntu 20.04). That at least runs, I'll try more tomorrow. Thanks!

**Comment by mvahowe** [comment]
I couldn't get the script to work with Ubuntu 20.04, but it worked out of the box with Ubuntu 22.04. I added a USX sample, added a gitignore for Jetbrains editors, and noted the Python 3.10 requirement in the readme.

**Review by mvahowe — APPROVED** [review]
This looks good! Thanks for the work!

**Pull request merged**
